### ISSUE TITLE
Add support for scss commentstring in vue files

### ISSUE THREAD

**Issue by wiwiiwiii** [suy/vim-context-commentstring#10]
Hello, thanks for the effort. So far so good.

Could you please add context commentstring for scss in vue files whose syntax group is `vue_scss`? Saves me the effort of adding this in vimrc, which could cause some trouble of defining order when sourcing vimrc.

Many thanks.

**Comment by suy** [comment]
Hello, and thanks for the feedback.

I can't specifically add this, because I can't test it. I don't use or know about vue, and I remember little about SCSS.

What's the problem with loading order? I'm not aware of this.

One benefit of setting this in your config is that you can have your setting for your own syntax highlighting. Given that there are different packages for syntax highlighting for the same language(s), I'm not sure how to provide support for this (it's very likely possible, but I have little time to spend on this because this are languages that I don't use myself).

**Comment by wiwiiwiii** [comment]
Thanks for the response, and sorry for not being clear enough.

I opened a PR [#11](https://github.com/suy/vim-context-commentstring/pull/11) to explain myself better. It is just one more simple line of code.

Nice plugin BTW.

**Comment by suy** [comment]
Thanks, this seems simple and safe enough to merge right away. If you don't mind though, can you mention which syntax plugin are you using? I maybe need to review the plugin when I have some time, and I'd like to have something to test on for regressions.

**Comment by wiwiiwiii** [comment]
Sure, I am currently using [vim-polyglot](https://github.com/sheerun/vim-polyglot).
